### ISSUE TITLE
ArmNN bug tracker

### ISSUE THREAD

**Issue by psyhtest** [ARM-software/armnn-mlperf#1]
This issue lists all reported bugs affecting porting of MLPerf benchmarks for ArmNN:
- [ ] https://github.com/ARM-software/armnn/issues/229 (ArmNN portability - more unused headers)
- [x] https://github.com/ARM-software/armnn/issues/227 (ArmNN portability - unused headers)
- [ ] https://github.com/ARM-software/armnn/issues/226 (ArmNN build stability - linking with Boost)
- [ ] https://github.com/ARM-software/armnn/issues/200 (ONNX parser for MobileNet / SSD-MobileNet)
- [ ] https://github.com/ARM-software/armnn/issues/199 (ONNX parser for ResNet / SSD-ResNet)
- [ ] https://github.com/ARM-software/armnn/issues/198 (ArmNN dev)
- [x] https://github.com/ARM-software/armnn/issues/196 (TFLite parser)
- [ ] https://github.com/ARM-software/armnn/issues/189 (TF parser for SSD-MobileNet)
- [ ] https://github.com/ARM-software/armnn/issues/150 (`tflite::TensorType_INT64` for ResNet)

**Comment by psyhtest** [comment]
@MatthewARM @sztaylor @robell

**Comment by psyhtest** [comment]
- [ ] [mlperf/inference/#229](https://github.com/mlperf/inference/issues/229) (TFLite-friendly SSD-ResNet)
